# Following https://github.com/lcswillems/rl-starter-files
MiniGrid-SimpleCrossingS9N1-v0:
  env_wrapper:
    - gym_minigrid.wrappers.RGBImgObsWrapper
    - gym_minigrid.wrappers.ImgObsWrapper
  normalize: true
  n_envs: 8 # number of environment copies running in parallel
  n_timesteps: !!float 1e6
  policy: 'CnnPolicy'
  n_steps: 512 # batch size is n_steps * n_env
  nminibatches: 32 # Number of training minibatches per update
  lam: 0.95 #  Factor for trade-off of bias vs variance for Generalized Advantage Estimator
  gamma: 0.99
  noptepochs: 10 #  Number of epoch when optimizing the surrogate
  ent_coef: 0.0 # Entropy coefficient for the loss caculation
  learning_rate: 2.5e-4 # The learning rate, it can be a function
  cliprange: 0.2 # Clipping parameter, it can be a function

MiniGrid-SimpleCrossingEnvUmaze-v0:
  env_wrapper:
    - gym_minigrid.wrappers.RGBImgObsWrapper
    - gym_minigrid.wrappers.ImgObsWrapper
  normalize: true
  n_envs: 8
  n_timesteps: !!float 1e6
  policy: 'CnnPolicy'
  n_steps: 512
  nminibatches: 32
  lam: 0.95
  gamma: 0.99
  noptepochs: 10
  ent_coef: 0.0
  learning_rate: 2.5e-4
  cliprange: 0.2
